api:
  requestTimeoutMillis: 5000
  textValidationUrl: localhost:8081
  userServiceUrl: localhost:8082

spring:
  data:
    mongodb:
      database: global-transactions-db
      auto-index-creation: true
